//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vendingDmytroKosanyakVoloshyn.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("vendingDmytroKosanyakVoloshyn.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Cents_euro_50 {
            get {
                object obj = ResourceManager.GetObject("Cents_euro_50", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Cents_euro_501 {
            get {
                object obj = ResourceManager.GetObject("Cents_euro_501", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Coca_Cola {
            get {
                object obj = ResourceManager.GetObject("Coca_Cola", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Coca_Cola1 {
            get {
                object obj = ResourceManager.GetObject("Coca_Cola1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Coins_taking {
            get {
                object obj = ResourceManager.GetObject("Coins_taking", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap en {
            get {
                object obj = ResourceManager.GetObject("en", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap en1 {
            get {
                object obj = ResourceManager.GetObject("en1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Coca Cola &lt;br&gt;
        /// &lt;br&gt;
        ///Cantidad por 100 gramos  &lt;br&gt;
        ///Calorías 38 &lt;br&gt;
        ///Grasas totales 0 g	 &lt;br&gt;
        ///Ácidos grasos saturados 0 g	 &lt;br&gt;
        ///Colesterol 0 mg	 &lt;br&gt;
        ///Sodio 4 mg	 &lt;br&gt;
        ///Potasio 2 mg	 &lt;br&gt;
        ///Hidratos de carbono 10 g	 &lt;br&gt;
        ///Fibra alimentaria 0 g	 &lt;br&gt;
        ///Azúcares 9 g	 &lt;br&gt;
        ///Proteínas 0,1 g	 &lt;br&gt;
        ///Cafeína 8 mg	 &lt;br&gt;
        ///Vitamina C	0 mg	Calcio	2 mg &lt;br&gt;
        ///Hierro	0,1 mg	Vitamina D	0 IU &lt;br&gt;
        ///Vitamina B6	0 mg	Vitamina B12	0 µg &lt;br&gt;
        ///Magnesio	0 mg	 &lt;br&gt;
        ///&lt;br&gt;
        ///Fanta Limón &lt;br&gt;
        /// &lt;br&gt;
        ///Información nutricional (por 10 [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string en2 {
            get {
                return ResourceManager.GetString("en2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap es {
            get {
                object obj = ResourceManager.GetObject("es", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap es1 {
            get {
                object obj = ResourceManager.GetObject("es1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Coca Cola &lt;br&gt;
        /// &lt;br&gt;
        ///Cantidad por 100 gramos  &lt;br&gt;
        ///Calorías 38 &lt;br&gt;
        ///Grasas totales 0 g	 &lt;br&gt;
        ///Ácidos grasos saturados 0 g	 &lt;br&gt;
        ///Colesterol 0 mg	 &lt;br&gt;
        ///Sodio 4 mg	 &lt;br&gt;
        ///Potasio 2 mg	 &lt;br&gt;
        ///Hidratos de carbono 10 g	 &lt;br&gt;
        ///Fibra alimentaria 0 g	 &lt;br&gt;
        ///Azúcares 9 g	 &lt;br&gt;
        ///Proteínas 0,1 g	 &lt;br&gt;
        ///Cafeína 8 mg	 &lt;br&gt;
        ///Vitamina C	0 mg	Calcio	2 mg &lt;br&gt;
        ///Hierro	0,1 mg	Vitamina D	0 IU &lt;br&gt;
        ///Vitamina B6	0 mg	Vitamina B12	0 µg &lt;br&gt;
        ///Magnesio	0 mg	 &lt;br&gt;
        ///&lt;br&gt;
        ///Fanta Limón &lt;br&gt;
        /// &lt;br&gt;
        ///Información nutricional (por 10 [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string es2 {
            get {
                return ResourceManager.GetString("es2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Euro_1 {
            get {
                object obj = ResourceManager.GetObject("Euro_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Euro_11 {
            get {
                object obj = ResourceManager.GetObject("Euro_11", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Euro_2 {
            get {
                object obj = ResourceManager.GetObject("Euro_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Euro_21 {
            get {
                object obj = ResourceManager.GetObject("Euro_21", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Fanta_Lemon {
            get {
                object obj = ResourceManager.GetObject("Fanta_Lemon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Fanta_Lemon1 {
            get {
                object obj = ResourceManager.GetObject("Fanta_Lemon1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Fanta_Orange {
            get {
                object obj = ResourceManager.GetObject("Fanta_Orange", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Fanta_Orange1 {
            get {
                object obj = ResourceManager.GetObject("Fanta_Orange1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Jack_Daniel_s_Coca_Cola {
            get {
                object obj = ResourceManager.GetObject("Jack_Daniel_s_Coca_Cola", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Jack_Daniel_s_Cola_Cola1 {
            get {
                object obj = ResourceManager.GetObject("Jack_Daniel_s_Cola_Cola1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap retirar_Monedas {
            get {
                object obj = ResourceManager.GetObject("retirar_Monedas", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        internal static byte[] retirar_Monedas1 {
            get {
                object obj = ResourceManager.GetObject("retirar_Monedas1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tpv {
            get {
                object obj = ResourceManager.GetObject("tpv", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
